/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zcView;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import zcController.zcDatabase;
import zcController.zcTransaction;

/**
 *
 * @author rk
 */
public class zcDebit extends javax.swing.JInternalFrame {

    /**
     * Creates new form zcCredit
     */
    public zcDebit() {
        initComponents();
        con = zcController.zcConnection.rkConnection();
        db.rkAutoCompleted(new JComboBox[]{zc_Day, zc_Month, zc_Year, zcAC_Number});
        for (int i = 2018; i <= 2020; i++) {
            zc_Year.addItem(i + "");
        }
        AC_Name = db.DML("SELECT `acACHolderName`,`zcACNumber` FROM `zcaccount`");
        AC_Number = db.DML("SELECT `id`,`zcACNumber` FROM `zcaccount`");
        AC_Number.entrySet().forEach((e) -> {
            zcAC_Number.addItem((String) e.getKey());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zcAC_Number = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        zc_Month = new javax.swing.JComboBox<>();
        zc_Year = new javax.swing.JComboBox<>();
        zc_Day = new javax.swing.JComboBox<>();
        zcAC_holderName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        zcAC_holderAmount = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(61, 51, 51));
        setClosable(true);
        setTitle("Withdraw");

        zcAC_Number.setEditable(true);
        zcAC_Number.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Account Number" }));
        zcAC_Number.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                zcAC_NumberItemStateChanged(evt);
            }
        });
        zcAC_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zcAC_NumberActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel1.setText("A/C Number");

        zc_Month.setEditable(true);
        zc_Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        zc_Year.setEditable(true);
        zc_Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));
        zc_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zc_YearActionPerformed(evt);
            }
        });

        zc_Day.setEditable(true);
        zc_Day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        zc_Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zc_DayActionPerformed(evt);
            }
        });

        zcAC_holderName.setEditable(false);
        zcAC_holderName.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel3.setText("Amount");

        zcAC_holderAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zcAC_holderAmountKeyTyped(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(zc_Day, 0, 1, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(zcAC_Number, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(zcAC_holderAmount, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(zcAC_holderName))
                                        .addContainerGap())))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(zc_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zc_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(zcAC_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zc_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zc_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zc_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zcAC_holderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zcAC_holderAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zc_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zc_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zc_YearActionPerformed

    private void zcAC_holderAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zcAC_holderAmountKeyTyped
        /*if(!Character.isDigit(evt.getKeyChar()) || evt.getKeyCode() == 46){
            
        }*/
    }//GEN-LAST:event_zcAC_holderAmountKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            if ((0 == zcAC_Number.getSelectedIndex()) || (0 == zc_Day.getSelectedIndex()) || (0 == zc_Month.getSelectedIndex()) || (0 == zc_Year.getSelectedIndex())) {
                JOptionPane.showMessageDialog(this, "Full fill all details", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                ps = con.prepareStatement("SELECT * FROM `zctransaction` where zcACNumber='" + zcAC_Number.getSelectedItem() + "'ORDER BY `zctransaction`.`id` ASC LIMIT 1");
                rs = ps.executeQuery();
                if (rs.next()) {
                    int zcMonth = rs.getInt("zcMonth");
                    int zcDay = rs.getInt("zcDay");
                    int zcYear = rs.getInt("zcYear");
                    rs.close();
                    ps.close();
                    switch (zcMonth) {
                        case 1:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 7) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay) {
                                    setDebit(true);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                        case 2:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 8) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay) {
                                    setDebit(true);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                        case 3:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 9) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay) {
                                    setDebit(true);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                        case 4:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 10) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay) {
                                    setDebit(true);
                                    System.out.println(zc_Day.getSelectedItem());
                                    System.out.println(zcDay);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                        case 5:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 11) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay) {
                                    setDebit(true);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                        case 6:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 12) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay) {
                                    setDebit(true);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                        case 7:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 1) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay && Integer.parseInt(zc_Year.getSelectedItem().toString()) > zcYear) {
                                    setDebit(true);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                        case 8:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 2) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay && Integer.parseInt(zc_Year.getSelectedItem().toString()) > zcYear) {
                                    setDebit(true);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                        case 9:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 3) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay && Integer.parseInt(zc_Year.getSelectedItem().toString()) > zcYear) {
                                    setDebit(true);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                        case 10:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 4) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay && Integer.parseInt(zc_Year.getSelectedItem().toString()) > zcYear) {
                                    setDebit(true);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                        case 11:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 5) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay && Integer.parseInt(zc_Year.getSelectedItem().toString()) >= zcYear) {
                                    setDebit(true);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                        case 12:
                            if (Integer.parseInt(zc_Month.getSelectedItem().toString()) >= 6) {
                                if (Integer.parseInt(zc_Day.getSelectedItem().toString()) >= zcDay && Integer.parseInt(zc_Year.getSelectedItem().toString()) > zcYear) {
                                    setDebit(true);
                                } else {
                                    setDebit(false);
                                }
                            } else {
                                setDebit(false);
                            }
                            break;
                    }

                    if (isDebit()) {
                        String currentDate = zc_Day.getSelectedItem() + "/" + zc_Month.getSelectedItem() + "/" + zc_Year.getSelectedItem();
                        if (isWithdraw()) {
                            System.out.println("One Time those person can withdraw money");
                            ps = con.prepareStatement("SELECT * FROM `zctransaction` WHERE `zcACNumber`='" + zcAC_Number.getSelectedItem() + "' ORDER BY id DESC");
                            rs = ps.executeQuery();
                            if (rs.next()) {
                                double totalAmount = rs.getDouble("totalCredit");
                                double returnAmount = (totalAmount * 80) / 100;
                                double roi = 0.0;
                                double totalDays;
                                double rateOfinterest = 0.0;
                                double rateOfinterestTotal = 0.0;
                                double perDayInterest = 0.0;
                                ps.close();
                                rs.close();

                                if (Double.parseDouble(zcAC_holderAmount.getText()) >= returnAmount) {
                                    JOptionPane.showMessageDialog(this, "can't withdraw amount more then " + returnAmount);
                                } else {
                                    ps = con.prepareStatement("SELECT * FROM `zctransaction` WHERE `zcACNumber`='" + zcAC_Number.getSelectedItem() + "' ORDER BY id DESC");
                                    rs = ps.executeQuery();
                                    while (rs.next()) {
                                        if ("Debit".equals(rs.getString("zcACtype"))) {
                                            String investmentDate = rs.getString("zcDay") + "/" + rs.getString("zcMonth") + "/" + rs.getString("zcYear");
                                            totalDays = zcController.zcCountDay.getDiiff(investmentDate, currentDate);
                                            roi = totalDays * 0.010958904;
                                            perDayInterest = rs.getDouble("totalCredit");
                                            rateOfinterest = (perDayInterest * roi) / 100;
                                            rateOfinterestTotal += rateOfinterest;
                                            perDayInterest = 0.0;
                                            System.out.println("Debit Amount");
                                            System.out.println("Total Days :- " + totalDays);
                                            System.out.println("Rate of Interest :- " + rateOfinterest);
                                            System.out.println("Total Rate of Interest :- " + rateOfinterestTotal);
                                            System.out.println("----------------------------------------------------");

                                            break;
                                        } else {
                                            String investmentDate = rs.getString("zcDay") + "/" + rs.getString("zcMonth") + "/" + rs.getString("zcYear");
                                            totalDays = zcController.zcCountDay.getDiiff(investmentDate, currentDate);
                                            roi = totalDays * 0.010958904;
                                            perDayInterest = rs.getDouble("zcAmount");
                                            rateOfinterest = (perDayInterest * roi) / 100;
                                            rateOfinterestTotal += rateOfinterest;
                                            perDayInterest = 0.0;
                                            System.out.println("Total Days :- " + totalDays);
                                            System.out.println("Rate of Interest :- " + rateOfinterest);
                                            System.out.println("Total Rate of Interest :- " + rateOfinterestTotal);
                                            System.out.println("----------------------------------------------------");

                                        }
                                    }
                                    ps = con.prepareStatement("INSERT INTO `zctransaction`(`zcACID`, `zcACNumber`, `zcAmount`, `zcACtype`, `zcDay`, `zcMonth`, `zcYear`,`totalCredit`,`rate`) VALUES (?,?,?,?,?,?,?,?,?)");
                                    ps.setString(1, (String) AC_Number.get(zcAC_Number.getSelectedItem()));
                                    ps.setString(2, (String) zcAC_Number.getSelectedItem());
                                    ps.setString(3, zcAC_holderAmount.getText());
                                    ps.setString(4, "Debit");
                                    ps.setString(5, (String) zc_Day.getSelectedItem());
                                    ps.setString(6, (String) zc_Month.getSelectedItem());
                                    ps.setString(7, (String) zc_Year.getSelectedItem());
                                    ps.setDouble(8, totalAmount - Double.parseDouble(zcAC_holderAmount.getText()));
                                    ps.setDouble(9, rateOfinterestTotal);
                                    ps.execute();
                                    JOptionPane.showMessageDialog(this, "Your Amount Sucessfully Withdraw");
                                    this.hide();
                                }
                            }
                        } else {
                            ps = con.prepareStatement("SELECT SUM(zcAmount) FROM zctransaction where zcACNumber = '" + zcAC_Number.getSelectedItem() + "'");
                            rs = ps.executeQuery();
                            if (rs.next()) {
                                double totalAmount = rs.getDouble(1);
                                double returnAmount = (totalAmount * 80) / 100;
                                double roi = 0.0;
                                double totalDays;
                                double rateOfinterest = 0.0;
                                double rateOfinterestTotal = 0.0;
                                double perDayInterest = 0.0;
                                ps.close();
                                rs.close();

                                if (Double.parseDouble(zcAC_holderAmount.getText()) >= returnAmount) {
                                    JOptionPane.showMessageDialog(this, "can't withdraw amount more then " + returnAmount);
                                } else {
                                    ps = con.prepareStatement("SELECT * FROM `zctransaction` WHERE `zcACNumber`='" + zcAC_Number.getSelectedItem() + "'");
                                    rs = ps.executeQuery();
                                    while (rs.next()) {
                                        String investmentDate = rs.getString("zcDay") + "/" + rs.getString("zcMonth") + "/" + rs.getString("zcYear");
                                        totalDays = zcController.zcCountDay.getDiiff(investmentDate, currentDate);
                                        roi = totalDays * 0.010958904;
                                        perDayInterest = rs.getDouble("zcAmount");
                                        rateOfinterest = (perDayInterest * roi) / 100;
                                        rateOfinterestTotal += rateOfinterest;
                                        perDayInterest = 0.0;
                                    }
                                    ps = con.prepareStatement("INSERT INTO `zctransaction`(`zcACID`, `zcACNumber`, `zcAmount`, `zcACtype`, `zcDay`, `zcMonth`, `zcYear`,`totalCredit`,`rate`) VALUES (?,?,?,?,?,?,?,?,?)");
                                    ps.setString(1, (String) AC_Number.get(zcAC_Number.getSelectedItem()));
                                    ps.setString(2, (String) zcAC_Number.getSelectedItem());
                                    ps.setString(3, zcAC_holderAmount.getText());
                                    ps.setString(4, "Debit");
                                    ps.setString(5, (String) zc_Day.getSelectedItem());
                                    ps.setString(6, (String) zc_Month.getSelectedItem());
                                    ps.setString(7, (String) zc_Year.getSelectedItem());
                                    ps.setDouble(8, totalAmount - Double.parseDouble(zcAC_holderAmount.getText()));
                                    ps.setDouble(9, rateOfinterestTotal);
                                    ps.execute();
                                    JOptionPane.showMessageDialog(this, "Your Amount Sucessfully Withdraw");
                                    this.hide();
                                }
                            } else {
                                System.out.println("record can't find");
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "can't withdraw amount before 6 month");
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(zcDebit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void zcAC_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zcAC_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zcAC_NumberActionPerformed

    private void zcAC_NumberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_zcAC_NumberItemStateChanged
        zcAC_holderName.setText((String) AC_Name.get(zcAC_Number.getSelectedItem()));
    }//GEN-LAST:event_zcAC_NumberItemStateChanged

    private void zc_DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zc_DayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zc_DayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> zcAC_Number;
    private javax.swing.JTextField zcAC_holderAmount;
    private javax.swing.JTextField zcAC_holderName;
    private javax.swing.JComboBox<String> zc_Day;
    private javax.swing.JComboBox<String> zc_Month;
    private javax.swing.JComboBox<String> zc_Year;
    // End of variables declaration//GEN-END:variables
    zcDatabase db = new zcDatabase();
    HashMap<Object, Object> AC_Name = new HashMap<>();
    HashMap<Object, Object> AC_Number = new HashMap<>();
    List<zcTransaction> list = new ArrayList<>();
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    private boolean debit;

    public boolean isDebit() {
        return debit;
    }

    public void setDebit(boolean debit) {
        this.debit = debit;
    }

    private String toDate(long timestamp) {
        Date date = new Date(timestamp * 1000);
        return new SimpleDateFormat("dd/MM/yyyy").format(date);
    }

    private boolean isWithdraw() {
        try {
            ps = con.prepareStatement("SELECT * FROM `zctransaction` WHERE `zcACNumber` = '" + zcAC_Number.getSelectedItem() + "' && `zcACtype`='Debit'");
            rs = ps.executeQuery();
            return rs.next();
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    private List<zcTransaction> zcTrasaction() {
        try {
            ps = con.prepareStatement("SELECT * FROM zctransaction where zcACNumber = '" + zcAC_Number.getSelectedItem() + "'");
            rs = ps.executeQuery();
            while (rs.next()) {
                zcTransaction transaction = new zcTransaction(
                        rs.getInt(1),
                        rs.getInt(2),
                        rs.getInt(3),
                        rs.getDouble(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7),
                        rs.getString(8),
                        rs.getString(9),
                        rs.getDouble(10),
                        rs.getDouble(11));
                list.add(transaction);
            }
            ps.close();
            rs.close();
            return list;
        } catch (SQLException E) {
            return null;
        }
    }
}
