package zcView;

import java.awt.Toolkit;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import zcController.*;

/**
 *
 * @author rk
 */
public class ZCMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form RKlogin
     */
    public ZCMainScreen() {
            
    }
    public ZCMainScreen(String value){
        initComponents();
        this.setLocationRelativeTo(null);
    //    this.setIconImage(Toolkit.getDefaultToolkit().getImage("RKinfotech/Image/RKLogo.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        zcCredit = new javax.swing.JButton();
        zcDebit = new javax.swing.JButton();
        zcReports = new javax.swing.JButton();
        zcSetting = new javax.swing.JButton();
        zcHome = new javax.swing.JButton();
        zcLogout = new javax.swing.JButton();
        Login = new javax.swing.JPanel();
        zcUserName = new javax.swing.JTextField();
        RKLogin = new javax.swing.JButton();
        zcPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rkDP = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PMS");
        setBackground(new java.awt.Color(61, 51, 51));
        setForeground(new java.awt.Color(61, 51, 51));
        setResizable(false);
        getContentPane().setLayout(null);

        Menu.setBackground(new java.awt.Color(61, 51, 51));

        zcCredit.setBackground(new java.awt.Color(51, 51, 255));
        zcCredit.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        zcCredit.setForeground(new java.awt.Color(255, 255, 255));
        zcCredit.setText("Credit");
        zcCredit.setEnabled(false);
        zcCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zcCreditActionPerformed(evt);
            }
        });

        zcDebit.setBackground(new java.awt.Color(51, 51, 255));
        zcDebit.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        zcDebit.setForeground(new java.awt.Color(255, 255, 255));
        zcDebit.setText("Debit");
        zcDebit.setEnabled(false);
        zcDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zcDebitActionPerformed(evt);
            }
        });

        zcReports.setBackground(new java.awt.Color(51, 51, 255));
        zcReports.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        zcReports.setForeground(new java.awt.Color(255, 255, 255));
        zcReports.setText("Reports");
        zcReports.setEnabled(false);
        zcReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zcReportsActionPerformed(evt);
            }
        });

        zcSetting.setBackground(new java.awt.Color(51, 51, 255));
        zcSetting.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        zcSetting.setForeground(new java.awt.Color(255, 255, 255));
        zcSetting.setText("Setting");
        zcSetting.setEnabled(false);
        zcSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zcSettingActionPerformed(evt);
            }
        });

        zcHome.setBackground(new java.awt.Color(0, 0, 255));
        zcHome.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        zcHome.setForeground(new java.awt.Color(255, 255, 255));
        zcHome.setText("Home");
        zcHome.setEnabled(false);
        zcHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zcHomeActionPerformed(evt);
            }
        });

        zcLogout.setBackground(new java.awt.Color(255, 51, 51));
        zcLogout.setFont(new java.awt.Font("DejaVu Sans", 3, 14)); // NOI18N
        zcLogout.setForeground(new java.awt.Color(51, 51, 51));
        zcLogout.setText("Logout");
        zcLogout.setEnabled(false);
        zcLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zcLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zcSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zcReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zcDebit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zcCredit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(zcHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zcLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zcHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(zcCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(zcDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(zcReports, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(zcSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 29, Short.MAX_VALUE)
                .addComponent(zcLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Menu);
        Menu.setBounds(0, 0, 221, 463);

        Login.setBackground(new java.awt.Color(61, 51, 51));
        Login.setLayout(null);

        zcUserName.setBackground(new java.awt.Color(51, 51, 51));
        zcUserName.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        zcUserName.setForeground(new java.awt.Color(255, 255, 255));
        zcUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        zcUserName.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Login.add(zcUserName);
        zcUserName.setBounds(200, 171, 250, 30);

        RKLogin.setBackground(new java.awt.Color(0, 51, 204));
        RKLogin.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        RKLogin.setText("Login");
        RKLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RKLoginActionPerformed(evt);
            }
        });
        Login.add(RKLogin);
        RKLogin.setBounds(370, 330, 90, 40);

        zcPassword.setBackground(new java.awt.Color(51, 51, 51));
        zcPassword.setForeground(new java.awt.Color(255, 255, 255));
        zcPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        zcPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Login.add(zcPassword);
        zcPassword.setBounds(200, 248, 250, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zcModel/Login.jpg"))); // NOI18N
        Login.add(jLabel1);
        jLabel1.setBounds(20, 0, 590, 460);

        getContentPane().add(Login);
        Login.setBounds(220, 0, 630, 470);

        jScrollPane1.setBackground(new java.awt.Color(61, 51, 51));

        rkDP.setBackground(new java.awt.Color(61, 51, 51));
        jScrollPane1.setViewportView(rkDP);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(222, 0, 630, 463);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zcCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zcCreditActionPerformed
        
    }//GEN-LAST:event_zcCreditActionPerformed

    private void zcSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zcSettingActionPerformed

    }//GEN-LAST:event_zcSettingActionPerformed

    private void zcHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zcHomeActionPerformed
       
    }//GEN-LAST:event_zcHomeActionPerformed

    private void zcDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zcDebitActionPerformed
        
    }//GEN-LAST:event_zcDebitActionPerformed

    private void RKLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RKLoginActionPerformed
        try {
            if (zcUserName.getText().isEmpty() || zcUserName.getText().equals("")) {
                JOptionPane.showMessageDialog(this, zcValidation.printErrorStatic("Invalid User Name"), "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (zcPassword.getText().isEmpty() || zcPassword.getPassword().equals("")) {
                    JOptionPane.showMessageDialog(this, zcValidation.printErrorStatic("Invalid PassWors"), "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    zcPassword.setText(zcMD5.getMD5(zcPassword.getText()));
                    zcUserName.setText(zcMD5.getMD5(zcUserName.getText()));
                    ResultSet rs = db.rkSelect_rs("SELECT * FROM `zclogin` WHERE `userName` ='" + zcUserName.getText() + "' AND `userPass` ='" + zcPassword.getText() + "'");
                    if (rs.next()) {
                        Login.setVisible(false);
                        zcHome.setEnabled(true);
                        zcCredit.setEnabled(true);
                        zcDebit.setEnabled(true);
                        zcReports.setEnabled(true);
                        zcSetting.setEnabled(false);
                        zcLogout.setEnabled(true);
                        zcUserName.setText("");
                        zcPassword.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, zcValidation.printErrorStatic("Invalid Username And Password"), "Error", JOptionPane.ERROR_MESSAGE);
                        zcPassword.setText("");
                        zcUserName.requestFocus();
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, zcValidation.printErrorStatic("Contact to Admin..", e.getMessage()));
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(ZCMainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RKLoginActionPerformed

    private void zcLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zcLogoutActionPerformed
        if (zcLogout.getText().equals("Logout")) {
            Login.setVisible(true);
            zcHome.setEnabled(false);
            zcCredit.setEnabled(false);
            zcDebit.setEnabled(false);
            zcReports.setEnabled(false);
            zcSetting.setEnabled(false);
            zcLogout.setEnabled(false);
        }
    }//GEN-LAST:event_zcLogoutActionPerformed

    private void zcReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zcReportsActionPerformed
        zcOpen.frame(new zcCredit(), rkDP);
    }//GEN-LAST:event_zcReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZCMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ZCMainScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton RKLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDesktopPane rkDP;
    private javax.swing.JButton zcCredit;
    private javax.swing.JButton zcDebit;
    private javax.swing.JButton zcHome;
    private javax.swing.JButton zcLogout;
    private javax.swing.JPasswordField zcPassword;
    private javax.swing.JButton zcReports;
    private javax.swing.JButton zcSetting;
    private javax.swing.JTextField zcUserName;
    // End of variables declaration//GEN-END:variables
    zcDatabase db = new zcDatabase();
}
